### ISSUE TITLE
Add option to detect whether the string start by the word searched

### ISSUE THREAD

**Issue by carluqcor** [jesusrp98/search_page#1]
If you search male with this plugin will also display female because it contains 'male'. So maybe adding a not required boolean to force it to follow a specific pattern (eg. must start with the name that you are searching for). 

Example:
Male (boolean var to True) -> Just display male people
Male (boolean var to False (By default should be false)) -> Display all pattern that contains M/male

**Comment by jesusrp98** [comment]
Nice idea, hopefully this feature will be implemented in the v1.2 update later this week.

More details about the implementation will be available later.

Thanks :)

**Comment by jesusrp98** [comment]
This feature has now been implemented inside the `master` branch.

You have now two new parameters: `itemStartsWith` and `itemEndsWith`:
- With `itemStartsWith` the package checks with the begining of each string item's representation.
- With `itemEndsWith` idem, but with the end of each string.
- With both of them set to `true`, you effectively have a perfect-matching way of filtering. You'd have to write the whole query in order to the filter process to succeed.

There's now more testing to be done, but this feature should land at the `pub.dev` repo in the coming days.

Thanks for the feedback @i62lucoc!!

**Comment by jesusrp98** [comment]
This feature has now been implemented in the v1.2 update, and it's available in the `pub.dev` repo.
