### ISSUE TITLE
Suggestion: property "items" could be a future

### ISSUE THREAD

**Issue by FelipeSamuel** [jesusrp98/search_page#17]
It would be useful if the "Items" property were a future. So we could query data from an API or database directly.

I loved this package.

**Comment by jesusrp98** [comment]
In the lines of #14 , the way the `SearchDelegate` class used by this package makes so that the feature is very restrictive. I'd suggest you wait for the future items to load, before opening the search page.

I'm really sorry the package can't support that user case :/

Maybe in the future I could rebuild the package from the ground up to support that kind of scenarios, that could be cool :)
